---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - view.vsix.wide.ad.jp
  resources:
  - markdownviews
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - view.vsix.wide.ad.jp
  resources:
  - markdownviews/finalizers
  verbs:
  - update
- apiGroups:
  - view.vsix.wide.ad.jp
  resources:
  - markdownviews/status
  verbs:
  - get
  - patch
  - update
